<!--<div class="block-content-wrap clearfix">-->
<!--	<div class="block-content sc-maxwidth">-->
<!--		<div class="my-wrap-block-content">-->
<!-- --><?//$APPLICATION->IncludeComponent(
//	"bitrix:news.list",
//	"my_home_projects",
//	Array(
//		"ACTIVE_DATE_FORMAT" => "j F Y",
//		"ADD_SECTIONS_CHAIN" => "N",
//		"AJAX_MODE" => "N",
//		"AJAX_OPTION_ADDITIONAL" => "",
//		"AJAX_OPTION_HISTORY" => "N",
//		"AJAX_OPTION_JUMP" => "N",
//		"AJAX_OPTION_STYLE" => "Y",
//		"CACHE_FILTER" => "N",
//		"CACHE_GROUPS" => "Y",
//		"CACHE_TIME" => "36000000",
//		"CACHE_TYPE" => "A",
//		"CHECK_DATES" => "Y",
//		"COMPONENT_TEMPLATE" => "home_projects",
//		"DETAIL_URL" => "",
//		"DISPLAY_BOTTOM_PAGER" => "N",
//		"DISPLAY_DATE" => "Y",
//		"DISPLAY_DETAIL_BUTTON" => "Y",
//		"DISPLAY_NAME" => "Y",
//		"DISPLAY_PICTURE" => "Y",
//		"DISPLAY_PREVIEW_TEXT" => "N",
//		"DISPLAY_TOP_PAGER" => "N",
//		"FIELD_CODE" => array(0=>"PREVIEW_PICTURE",1=>"DETAIL_PICTURE",2=>"",),
//		"FILTER_NAME" => "",
//		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
//		"IBLOCK_ID" => "25",
//		"IBLOCK_TYPE" => "content",
//		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
//		"INCLUDE_SUBSECTIONS" => "Y",
//		"ITEMS_PER_ROW" => "4",
//		"MESSAGE_404" => "",
//		"NEWS_COUNT" => "20",
//		"PAGER_BASE_LINK_ENABLE" => "N",
//		"PAGER_DESC_NUMBERING" => "N",
//		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
//		"PAGER_SHOW_ALL" => "N",
//		"PAGER_SHOW_ALWAYS" => "N",
//		"PAGER_TEMPLATE" => "",
//		"PAGER_TITLE" => "Новости",
//		"PARENT_SECTION" => "22",
//		"PARENT_SECTION_CODE" => "",
//		"PREVIEW_TRUNCATE_LEN" => "",
//		"PROPERTY_CODE" => array(0=>"",1=>"",),
//		"SET_BROWSER_TITLE" => "N",
//		"SET_LAST_MODIFIED" => "N",
//		"SET_META_DESCRIPTION" => "N",
//		"SET_META_KEYWORDS" => "N",
//		"SET_STATUS_404" => "N",
//		"SET_TITLE" => "N",
//		"SHOW_404" => "N",
//		"SORT_BY1" => "SORT",
//		"SORT_BY2" => "ACTIVE_FROM",
//		"SORT_ORDER1" => "ASC",
//		"SORT_ORDER2" => "DESC"
//	)
//);?>
<!--		</div>-->
<!---->
<!--		<div class="my-wrap-block-content">-->
<?//$APPLICATION->IncludeComponent(
//	"bitrix:news.list",
//	"my_home_projects2",
//	Array(
//		"ACTIVE_DATE_FORMAT" => "j F Y",
//		"ADD_SECTIONS_CHAIN" => "N",
//		"AJAX_MODE" => "N",
//		"AJAX_OPTION_ADDITIONAL" => "",
//		"AJAX_OPTION_HISTORY" => "N",
//		"AJAX_OPTION_JUMP" => "N",
//		"AJAX_OPTION_STYLE" => "Y",
//		"CACHE_FILTER" => "N",
//		"CACHE_GROUPS" => "Y",
//		"CACHE_TIME" => "36000000",
//		"CACHE_TYPE" => "A",
//		"CHECK_DATES" => "Y",
//		"COMPONENT_TEMPLATE" => "home_projects",
//		"DETAIL_URL" => "",
//		"DISPLAY_BOTTOM_PAGER" => "N",
//		"DISPLAY_DATE" => "Y",
//		"DISPLAY_DETAIL_BUTTON" => "Y",
//		"DISPLAY_NAME" => "Y",
//		"DISPLAY_PICTURE" => "Y",
//		"DISPLAY_PREVIEW_TEXT" => "N",
//		"DISPLAY_TOP_PAGER" => "N",
//		"FIELD_CODE" => array(0=>"PREVIEW_PICTURE",1=>"DETAIL_PICTURE",2=>"",),
//		"FILTER_NAME" => "",
//		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
//		"IBLOCK_ID" => "25",
//		"IBLOCK_TYPE" => "content",
//		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
//		"INCLUDE_SUBSECTIONS" => "Y",
//		"ITEMS_PER_ROW" => "4",
//		"MESSAGE_404" => "",
//		"NEWS_COUNT" => "20",
//		"PAGER_BASE_LINK_ENABLE" => "N",
//		"PAGER_DESC_NUMBERING" => "N",
//		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
//		"PAGER_SHOW_ALL" => "N",
//		"PAGER_SHOW_ALWAYS" => "N",
//		"PAGER_TEMPLATE" => "",
//		"PAGER_TITLE" => "Tttt",
//		"PARENT_SECTION" => "23",
//		"PARENT_SECTION_CODE" => "",
//		"PREVIEW_TRUNCATE_LEN" => "",
//		"PROPERTY_CODE" => array(0=>"",1=>"",),
//		"SET_BROWSER_TITLE" => "N",
//		"SET_LAST_MODIFIED" => "N",
//		"SET_META_DESCRIPTION" => "N",
//		"SET_META_KEYWORDS" => "N",
//		"SET_STATUS_404" => "N",
//		"SET_TITLE" => "N",
//		"SHOW_404" => "N",
//		"SORT_BY1" => "SORT",
//		"SORT_BY2" => "ACTIVE_FROM",
//		"SORT_ORDER1" => "ASC",
//		"SORT_ORDER2" => "DESC"
//	)
//);?>
<!---->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->
