<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Реквизиты");
?><p>
	 В таблице указаны реквизиты компании. Для социальных животных характерно выделение из общей среды лидера (вожака), функцией которого становится поддержание внутренней иерархии при собственном доминирующем положении.
</p>
<h2>Реквизиты</h2>
<table class="table table-bordered table-responsive table-striped">
<tbody>
<tr>
	<td>
		 Название
	</td>
	<td>
		 ООО «Название компании»
	</td>
</tr>
<tr>
	<td>
		 ОГРН
	</td>
	<td>
		 1122334455667
	</td>
</tr>
<tr>
	<td>
		 ИНН / КПП
	</td>
	<td>
		 2233445566 / 223344556
	</td>
</tr>
<tr>
	<td>
		 р/сч.
	</td>
	<td>
		 86584575475475475475
	</td>
</tr>
<tr>
	<td>
		 Корр/субсчет
	</td>
	<td>
		 67695685685685685686
	</td>
</tr>
<tr>
	<td>
		 БИК
	</td>
	<td>
		 945754757
	</td>
</tr>
</tbody>
</table><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>